/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import core.Pobocka;
import splay.InformacnySystem;
import splay.Node;

/**
 *
 * @author tomas
 */
public class FramePobocka extends javax.swing.JFrame {

    private InformacnySystem informacnySystem;
    private String nazovPobocky;
    
    public FramePobocka(String nazovPobocky,InformacnySystem informacnySystem) {
        this.nazovPobocky=nazovPobocky;
        this.informacnySystem=informacnySystem;
        initComponents();
        this.setLocation(500,500);
    }

    public String getNazovPobocky() {
        return nazovPobocky;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPobocka = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVypisKnih = new javax.swing.JButton();
        btnNajdiKnihu = new javax.swing.JButton();
        btnPozicaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPobocka.setColumns(20);
        txtPobocka.setRows(5);
        jScrollPane1.setViewportView(txtPobocka);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nachádzate sa na pobočke "+this.getNazovPobocky());

        btnVypisKnih.setText("Výpis kníh (7)");
        btnVypisKnih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVypisKnihActionPerformed(evt);
            }
        });

        btnNajdiKnihu.setText("Nájdi knihu (1)");
        btnNajdiKnihu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNajdiKnihuActionPerformed(evt);
            }
        });

        btnPozicaj.setText("Požičaj knhu (3)");
        btnPozicaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPozicajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVypisKnih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNajdiKnihu, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnPozicaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVypisKnih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNajdiKnihu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPozicaj)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVypisKnihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVypisKnihActionPerformed
        txtPobocka.setText(informacnySystem.najdiPobocku(nazovPobocky).getKnihyNazvov().InOrderPrint());       
    }//GEN-LAST:event_btnVypisKnihActionPerformed

    private void btnNajdiKnihuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNajdiKnihuActionPerformed
        DialogNajdiKnihu dialog=new DialogNajdiKnihu(this, rootPaneCheckingEnabled);
        System.out.println(dialog.getIdKnihy());
       int idKnihy=dialog.getIdKnihy();
       //String  nazovPobocky=dialog.getNazovPobocky();         
       txtPobocka.setText(informacnySystem.najdiKnihu(idKnihy, nazovPobocky).udaje());
    }//GEN-LAST:event_btnNajdiKnihuActionPerformed

    private void btnPozicajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPozicajActionPerformed
       DialogPozicajKnihu dialog=new DialogPozicajKnihu(this, rootPaneCheckingEnabled);
       int idKnihy=dialog.getIdKnihy();       
       String idCitatela=dialog.getIdCitatela();
        System.out.println(idKnihy+" "+idCitatela+" "+nazovPobocky);
       informacnySystem.pozicajKnihu(idKnihy,idCitatela, nazovPobocky);
       
    }//GEN-LAST:event_btnPozicajActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNajdiKnihu;
    private javax.swing.JButton btnPozicaj;
    private javax.swing.JButton btnVypisKnih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPobocka;
    // End of variables declaration//GEN-END:variables
}
