/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import splay.InformacnySystem;

/**
 *
 * @author tomas
 */
public class FrameHlavne extends javax.swing.JFrame {

    private InformacnySystem informacnySystem;

    public FrameHlavne() {
        informacnySystem = new InformacnySystem();
        this.setLocation(500, 500);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNadpis = new javax.swing.JLabel();
        btnVypCitatelov = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTxtAreaInfSystem = new javax.swing.JTextArea();
        btnVypPobociek = new javax.swing.JButton();
        btnNapln = new javax.swing.JButton();
        btnCitatelia = new javax.swing.JButton();
        btnKnihy = new javax.swing.JButton();
        btnPridajPobocku = new javax.swing.JButton();
        btnPobocka = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlblDatum = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnZmenDatum = new javax.swing.JButton();
        jSpinDen = new javax.swing.JSpinner();
        jSpinMesiac = new javax.swing.JSpinner();
        jSpinRok = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblNadpis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblNadpis.setText("Informačný systém ");

        btnVypCitatelov.setText("Výpis čitateľov (18)");
        btnVypCitatelov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVypCitatelovActionPerformed(evt);
            }
        });

        JTxtAreaInfSystem.setColumns(20);
        JTxtAreaInfSystem.setRows(5);
        jScrollPane1.setViewportView(JTxtAreaInfSystem);

        btnVypPobociek.setText("Výpis pobočiek (6)");
        btnVypPobociek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVypPobociekActionPerformed(evt);
            }
        });

        btnNapln.setText("Napln");
        btnNapln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaplnActionPerformed(evt);
            }
        });

        btnCitatelia.setText("Čitatelia");
        btnCitatelia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitateliaActionPerformed(evt);
            }
        });

        btnKnihy.setText("Knihy");
        btnKnihy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnihyActionPerformed(evt);
            }
        });

        btnPridajPobocku.setText("Pridaj pobočku (16)");
        btnPridajPobocku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridajPobockuActionPerformed(evt);
            }
        });

        btnPobocka.setText("Pobočka");
        btnPobocka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPobockaActionPerformed(evt);
            }
        });

        jButton1.setText("Pridaj knihu (10)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlblDatum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblDatum.setText(informacnySystem.vypisAktualntDatum());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("/");

        jLabel3.setText("/");

        btnZmenDatum.setText("Zmeň dátum");
        btnZmenDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZmenDatumActionPerformed(evt);
            }
        });

        jSpinDen.setValue(20);

        jSpinMesiac.setToolTipText("");
        jSpinMesiac.setValue(12);

        jSpinRok.setValue(2016);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLblNadpis, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSpinDen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinMesiac, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinRok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZmenDatum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlblDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVypCitatelov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVypPobociek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCitatelia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKnihy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPridajPobocku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPobocka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addComponent(btnNapln, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNadpis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVypPobociek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPridajPobocku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVypCitatelov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCitatelia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPobocka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKnihy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNapln)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinMesiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZmenDatum)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVypCitatelovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVypCitatelovActionPerformed
        JTxtAreaInfSystem.setText("");
        JTxtAreaInfSystem.append(informacnySystem.getCitatelia().InOrderPrint());
    }//GEN-LAST:event_btnVypCitatelovActionPerformed

    private void btnVypPobociekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVypPobociekActionPerformed
        JTxtAreaInfSystem.setText("");
        JTxtAreaInfSystem.append(informacnySystem.getPobocky().InOrderPrint());
    }//GEN-LAST:event_btnVypPobociekActionPerformed

    private void btnNaplnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaplnActionPerformed
        System.out.println("Data boli nacitane");
        informacnySystem.naplnSystem();
    }//GEN-LAST:event_btnNaplnActionPerformed

    private void btnCitateliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitateliaActionPerformed
        new FrameCitatelia(informacnySystem).setVisible(true);
    }//GEN-LAST:event_btnCitateliaActionPerformed

    private void btnKnihyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnihyActionPerformed
        new FrameKnihy(informacnySystem).setVisible(true);
    }//GEN-LAST:event_btnKnihyActionPerformed

    private void btnPridajPobockuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridajPobockuActionPerformed
        DialogDajPobocku dialog = new DialogDajPobocku(this);
        String nazov = dialog.getNazovPobocky();

        if (nazov != null) {
            informacnySystem.pridajPobocku(nazov);
        }        

    }//GEN-LAST:event_btnPridajPobockuActionPerformed

    private void btnPobockaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPobockaActionPerformed
        DialogDajPobocku dialog=new DialogDajPobocku(this);
        String nazov = dialog.getNazovPobocky();
       
        if (nazov != null) {
            new FramePobocka(nazov,informacnySystem).setVisible(true);
        }
        
    }//GEN-LAST:event_btnPobockaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DialogPridajKnihu dialog=new DialogPridajKnihu(this, rootPaneCheckingEnabled,informacnySystem);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnZmenDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZmenDatumActionPerformed
        int den=(int)(jSpinDen.getValue());
        int mesiac=(int)(jSpinMesiac.getValue());
        int rok=(int)(jSpinRok.getValue());
        informacnySystem.setAktualnyDatum(den, mesiac, rok);     
        jlblDatum.setText(informacnySystem.vypisAktualntDatum());
    }//GEN-LAST:event_btnZmenDatumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHlavne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHlavne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHlavne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHlavne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHlavne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTxtAreaInfSystem;
    private javax.swing.JButton btnCitatelia;
    private javax.swing.JButton btnKnihy;
    private javax.swing.JButton btnNapln;
    private javax.swing.JButton btnPobocka;
    private javax.swing.JButton btnPridajPobocku;
    private javax.swing.JButton btnVypCitatelov;
    private javax.swing.JButton btnVypPobociek;
    private javax.swing.JButton btnZmenDatum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblNadpis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinDen;
    private javax.swing.JSpinner jSpinMesiac;
    private javax.swing.JSpinner jSpinRok;
    private javax.swing.JLabel jlblDatum;
    // End of variables declaration//GEN-END:variables
}
