/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import splay.InformacnySystem;

/**
 *
 * @author tomas
 */
public class FrameCitatelia extends javax.swing.JFrame {

    private InformacnySystem informacnySystem;

    public FrameCitatelia(InformacnySystem informacnySystem) {
        this.informacnySystem = informacnySystem;
        initComponents();
        this.setLocation(500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaEvidenciaCitatelov = new javax.swing.JTextArea();
        btnVypisCitatelov = new javax.swing.JButton();
        btnPridanieCitatela = new javax.swing.JButton();
        btnZmazanieCitatela = new javax.swing.JButton();
        btnNajdiCitatela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Evidencia čitateľov");

        TxtAreaEvidenciaCitatelov.setColumns(20);
        TxtAreaEvidenciaCitatelov.setRows(5);
        jScrollPane1.setViewportView(TxtAreaEvidenciaCitatelov);

        btnVypisCitatelov.setText("Výpis čitateľov (18)");
        btnVypisCitatelov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVypisCitatelovActionPerformed(evt);
            }
        });

        btnPridanieCitatela.setText("Pridanie čitateľa (9)");
        btnPridanieCitatela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridanieCitatelaActionPerformed(evt);
            }
        });

        btnZmazanieCitatela.setText("Zmazanie čitateľa (15)");
        btnZmazanieCitatela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZmazanieCitatelaActionPerformed(evt);
            }
        });

        btnNajdiCitatela.setText("Nájdi čitateľa (5)");
        btnNajdiCitatela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNajdiCitatelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVypisCitatelov)
                        .addGap(18, 18, 18)
                        .addComponent(btnPridanieCitatela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZmazanieCitatela)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNajdiCitatela, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVypisCitatelov)
                    .addComponent(btnPridanieCitatela)
                    .addComponent(btnZmazanieCitatela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNajdiCitatela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVypisCitatelovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVypisCitatelovActionPerformed
        TxtAreaEvidenciaCitatelov.setText("");
        TxtAreaEvidenciaCitatelov.append(informacnySystem.getCitatelia().InOrderPrint());
    }//GEN-LAST:event_btnVypisCitatelovActionPerformed

    private void btnPridanieCitatelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridanieCitatelaActionPerformed
        DialogNovyCitatel dialog = new DialogNovyCitatel(this, rootPaneCheckingEnabled, informacnySystem);


    }//GEN-LAST:event_btnPridanieCitatelaActionPerformed

    private void btnNajdiCitatelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNajdiCitatelaActionPerformed
        DialogNajdiCitatela dialog = new DialogNajdiCitatela(this, rootPaneCheckingEnabled);
        String idPreukazu = dialog.getIdPreukazu();
        try {
            if (!idPreukazu.equals("")) {

                TxtAreaEvidenciaCitatelov.setText(informacnySystem.getCitatel(idPreukazu).toString() + "\nZoznam požičaných kníh: \n");
                TxtAreaEvidenciaCitatelov.append(informacnySystem.getCitatel(idPreukazu).getVypozicky().InOrderPrint());

            } else {
                System.out.println("Nezadal si id preukazu");
            }

        } catch (Exception e) {
            System.out.println("Uzivatel s danym preukazom neexituje");
        }
    }//GEN-LAST:event_btnNajdiCitatelaActionPerformed

    private void btnZmazanieCitatelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZmazanieCitatelaActionPerformed
            DialogNajdiCitatela dialog=new DialogNajdiCitatela(this, rootPaneCheckingEnabled);
            String cisloPreukazu=dialog.idPreukazu;
            informacnySystem.vymazCitatela(cisloPreukazu);
    }//GEN-LAST:event_btnZmazanieCitatelaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtAreaEvidenciaCitatelov;
    private javax.swing.JButton btnNajdiCitatela;
    private javax.swing.JButton btnPridanieCitatela;
    private javax.swing.JButton btnVypisCitatelov;
    private javax.swing.JButton btnZmazanieCitatela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
